name: issue discuss

on:
  [push, gollum, pull_request]
  

jobs:
  discuss:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      

    steps:
     - uses: Tyler887/autodiscuss@1.0
      
